import type { AdminLang } from './admin-lang'

const labels = {
  en: {
    dashboard: 'Dashboard',
    welcome: 'Welcome back 👋',
    welcomeSub: "Here's what's happening with your store today.",
    totalProducts: 'Total Products',
    totalStock: 'Total Stock Units',
    lowStockAlerts: 'Low Stock Alerts',
    mediaFiles: 'Media Files',
    lowStockWarnings: 'Low Stock Warnings',
    edit: 'Edit',
    allWellStocked: '✅ All products are well-stocked!',
    products: 'Products',
    newProduct: 'Add New Product',
    editProduct: 'Edit Product',
    delete: 'Delete',
    save: 'Save',
    cancel: 'Cancel',
    productNameAr: 'Product Name (Arabic)',
    price: 'Price',
    stock: 'Stock',
    available: 'Available',
    homepageEditor: 'Homepage Editor',
    saveChanges: 'Save All Changes',
    heroImage: 'Hero Image',
    headline: 'Headline',
    subheadline: 'Subheadline',
    announcementBar: 'Announcement Bar',
    showBar: 'Show Announcement Bar Sitewide',
    announcementText: 'Announcement Text',
    bgColor: 'Background Color',
    whatsappSettings: 'WhatsApp Settings',
    phoneNumber: 'Phone Number',
    saveNumber: 'Save Number',
    seoSettings: 'SEO Settings',
    pageTitle: 'Page Title',
    description: 'Description',
    keyword: 'Keyword',
    mediaLibrary: 'Media Library',
    ctaImage: 'CTA Featured Image',
    uploadFile: 'Upload File',
    signOut: 'Sign Out',
    signingOut: 'Signing out…',
    langToggle: 'عربي',
    lifestyleGallery: 'Lifestyle Gallery',
    contactPageEditor: 'Contact Page Editor',
  },
  ar: {
    dashboard: 'لوحة التحكم',
    welcome: 'مرحباً',
    welcomeSub: 'ده ملخص حالة المتجر النهاردة.',
    totalProducts: 'إجمالي المنتجات',
    totalStock: 'إجمالي المخزون',
    lowStockAlerts: 'تحذيرات مخزون منخفض',
    mediaFiles: 'ملفات الوسائط',
    lowStockWarnings: 'تحذيرات مخزون منخفض',
    edit: 'تعديل',
    allWellStocked: '✅ كل المنتجات متوفرة بكميات كافية!',
    products: 'المنتجات',
    newProduct: 'منتج جديد',
    editProduct: 'تعديل المنتج',
    delete: 'حذف',
    save: 'حفظ',
    cancel: 'إلغاء',
    productNameAr: 'اسم المنتج (عربي)',
    price: 'السعر',
    stock: 'المخزون',
    available: 'متاح',
    homepageEditor: 'محرر الصفحة الرئيسية',
    saveChanges: 'حفظ التغييرات',
    heroImage: 'صورة الهيرو',
    headline: 'العنوان الرئيسي',
    subheadline: 'العنوان الفرعي',
    announcementBar: 'شريط الإعلانات',
    showBar: 'إظهار الشريط',
    announcementText: 'نص الإعلان',
    bgColor: 'لون الخلفية',
    whatsappSettings: 'إعدادات واتساب',
    phoneNumber: 'رقم الهاتف',
    saveNumber: 'حفظ الرقم',
    seoSettings: 'إعدادات SEO',
    pageTitle: 'عنوان الصفحة',
    description: 'الوصف',
    keyword: 'الكلمة المفتاحية',
    mediaLibrary: 'مكتبة الوسائط',
    ctaImage: 'صورة CTA المميزة',
    uploadFile: 'رفع ملف',
    signOut: 'تسجيل الخروج',
    signingOut: 'بنسجل خروج…',
    langToggle: 'English',
    lifestyleGallery: 'معرض اللايف ستايل',
    contactPageEditor: 'محرر صفحة اتصل بنا',
  },
} as const

export type AdminLabelKey = keyof typeof labels.en

export function adminLabel(lang: AdminLang, key: AdminLabelKey): string {
  return labels[lang][key]
}

export const ADMIN_NAV: { href: string; labelKey: AdminLabelKey; icon: string }[] = [
  { href: '/admin/dashboard', labelKey: 'dashboard', icon: 'LayoutDashboard' },
  { href: '/admin/products', labelKey: 'products', icon: 'Package' },
  { href: '/admin/homepage', labelKey: 'homepageEditor', icon: 'Home' },
  { href: '/admin/contact', labelKey: 'contactPageEditor', icon: 'PhoneCall' },
  { href: '/admin/whatsapp', labelKey: 'whatsappSettings', icon: 'MessageCircle' },
  { href: '/admin/announcement', labelKey: 'announcementBar', icon: 'Megaphone' },
  { href: '/admin/media', labelKey: 'mediaLibrary', icon: 'Image' },
  { href: '/admin/seo', labelKey: 'seoSettings', icon: 'Search' },
]
